package com.HashTable;

import java.util.HashMap;
import java.util.HashSet;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindtheDifference {
    public char findTheDifference(String s, String t) {
        HashMap<Character,Integer> hs=new HashMap();
        for(int i=0;i<t.length();i++) {
            hs.put(t.charAt(i), hs.getOrDefault(t.charAt(i), 0) + 1);
        }
        for(int i=0;i<s.length();i++){
            hs.put(s.charAt(i),hs.getOrDefault(s.charAt(i),0)-1);
        }

        for(int i=0;i<hs.size();i++){
            if(hs.get(t.charAt(i))==1){
                return t.charAt(i);
            }
        }
        return 0;
    }

    public char findTheDifferenceII(String s, String t) {
        int n = t.length();
        char c = t.charAt(n - 1);
        for (int i = 0; i < n - 1; ++i) {//异或的性质需要自己去关注一下
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }

    public static void main(String[]args){
        FindtheDifference test=new FindtheDifference();
        String s="abcd";
        String t="abcde";
        System.out.print(test.findTheDifference(s,t));
    }
}
